[versions]
accompanist = "0.37.3"
algolia = "3.39.2"
android-securityLints = "1.0.4"
# See https://developer.android.com/jetpack/androidx/releases/compose-kotlin
androidGradleCacheFix = "3.0.3"
# @pin needs to match libpebble3's plugin
androidGradlePlugin = "8.13.2"
androidx-activity-compose = "1.13.0"
androidx-annotation = "1.9.1"
androidx-compose-material3 = "1.5.0-alpha15"
androidx-compose-runtime = "1.10.5"
androidx-core = "1.18.0"
androidx-core-splashscreen = "1.2.0"
androidx-datastore = "1.2.1"
androidx-lifecycle = "2.10.0"
androidx-navigation3 = "1.0.1"
androidx-paging = "3.4.2"
androidx-startup = "1.2.0"
androidx-test-runner = "1.7.0"
androidx-work = "2.11.1"
coil = "3.4.0"
composeDnd = "0.4.0"
composePreference = "2.1.1"
composeWebview = "0.33.6"
dependencyAnalysis = "3.5.0"
desugarJdkLibs = "2.1.5"
detekt = "2.0.0-alpha.2"
detekt-compose = "0.5.6"
dispatch = "1.0.0-beta10"
foundationLayout = "1.10.5"
# @keep used in kts scripts directly
jacoco = "0.8.14"
jspecify = "1.0.0"
junit = "6.0.3"
junit4 = "4.13.2"
junit4-parameterinjector = "1.21"
kable = "0.42.0"
kermit = "2.1.0"
koin = "4.1.1"
kotest = "6.1.9"
# Temporarily use RC kotlin as a workaround for the https://github.com/ZacSweers/metro/issues/460
kotlin = "2.3.20"
kotlin-coroutines = "1.10.2"
kotlin-io = "0.9.0"
kotlin-serialization = "1.10.0"
kotlinova = "4.0.0-alpha16-mpp2"
ksp = "2.3.6"
ktor = "3.2.3"
libpebble3 = "0.0.0"
logcat = "0.4"
metro = "0.10.2"
moduleGraphAssert = "2.9.0"
okio = "3.16.4"
orgJson = "20251224"
paparazzi = "2.0.0-alpha04"
rebugger = "1.0.1"
showkase = "1.0.5"
# @pin It seems this is the latest stable version, we do not want `-dirty` version
speex = "1946c84"
tinylog = "2.7.0"
turbine = "1.2.1"
unmock-androidJar = "16-robolectric-13921718"
unmock-plugin = "0.9.0"
versionCatalogUpdate = "1.1.0"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
algolia = { module = "com.algolia:algoliasearch-client-kotlin", version.ref = "algolia" }
# Dummy entry, we don't need to actually use the stdlib explicitly, but it is used for the version checker to auto update kotlin
android-agp = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
android-securityLints = { module = "com.android.security.lint:lint", version.ref = "android-securityLints" }
androidGradleCacheFix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version.ref = "androidGradleCacheFix" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-material3-sizeClasses = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidx-compose-material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-runtime-annotation = { module = "androidx.compose.runtime:runtime-annotation", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-runtime" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose-runtime" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "foundationLayout" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation3 = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
composeDnd = { module = "com.mohamedrejeb.dnd:compose-dnd", version.ref = "composeDnd" }
composePreference = { module = "me.zhanghai.compose.preference:preference", version.ref = "composePreference" }
composeWebview = { module = "io.github.kevinnzou:compose-webview", version.ref = "composeWebview" }
dependencyAnalysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependencyAnalysis" }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
detekt-api = { module = "dev.detekt:detekt-api", version.ref = "detekt" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }
detekt-ktlint = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }
detekt-plugin = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
dispatch = { module = "com.rickbusarow.dispatch:dispatch-core", version.ref = "dispatch" }
dispatch-test = { module = "com.rickbusarow.dispatch:dispatch-test", version.ref = "dispatch" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
junit4-parameterinjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "junit4-parameterinjector" }
kable = { module = "com.juul.kable:kable-core", version.ref = "kable" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlin-io" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-plugin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-plugin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlinova-compose = { module = "si.inova.kotlinova:compose", version.ref = "kotlinova" }
kotlinova-core = { module = "si.inova.kotlinova:core", version.ref = "kotlinova" }
kotlinova-core-test = { module = "si.inova.kotlinova:core-test", version.ref = "kotlinova" }
kotlinova-gradle = { module = "si.inova.kotlinova:gradle", version.ref = "kotlinova" }
kotlinova-navigation = { module = "si.inova.kotlinova:navigation", version.ref = "kotlinova" }
kotlinova-navigation-compiler = { module = "si.inova.kotlinova:navigation-compiler", version.ref = "kotlinova" }
kotlinova-navigation-detekt = { module = "si.inova.kotlinova:navigation-detekt", version.ref = "kotlinova" }
kotlinova-navigation-navigation3 = { module = "si.inova.kotlinova:navigation-navigation3", version.ref = "kotlinova" }
kotlinova-navigation-test = { module = "si.inova.kotlinova:navigation-test", version.ref = "kotlinova" }
ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-io = { module = "io.ktor:ktor-io", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktor" }
# Synthetic library declaration that then gets replaced with the included libpebble3
libpebble3 = { module = "com.coredevices:libpebble3", version.ref = "libpebble3" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
metro-plugin = { module = "dev.zacsweers.metro:gradle-plugin", version.ref = "metro" }
moduleGraphAssert = { module = "com.jraska.module.graph.assertion:plugin", version.ref = "moduleGraphAssert" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
orgJson = { module = "org.json:json", version.ref = "orgJson" }
rebugger = { module = "io.github.theapache64:rebugger", version.ref = "rebugger" }
showkase = { module = "com.airbnb.android:showkase", version.ref = "showkase" }
showkase-processor = { module = "com.airbnb.android:showkase-processor", version.ref = "showkase" }
speex = { module = "io.github.coredevices.speex:speex", version.ref = "speex" }
tinylog-api = { module = "org.tinylog:tinylog-api-kotlin", version.ref = "tinylog" }
tinylog-impl = { module = "org.tinylog:tinylog-impl", version.ref = "tinylog" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
unmock-androidJar = { module = "org.robolectric:android-all", version.ref = "unmock-androidJar" }
unmock-plugin = { module = "com.github.bjoernq:unmockplugin", version.ref = "unmock-plugin" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
